# 시각화 (Visualization)

In [1]:
import numpy as np
import pandas as pd

In [2]:
import warnings

warnings.filterwarnings(action='ignore')
#  warnings.filterwarnings(action='default')

In [3]:
data = pd.read_csv("Busan_Covid-19.csv")

data

,date,day,total_coronic,new_coronic,total_be_cured,new_be_cured,deceased,total_negative,new_negative,diagnosed,isolated,total_released,new_released
0,2021-02-06,토,2879,11,2445,36,96,313750,2900,2911,5281,96416,433
1,2021-02-05,금,2868,15,2409,23,96,310850,1886,1901,5275,95983,413
2,2021-02-04,목,2853,34,2386,20,96,308964,2664,2698,5289,95570,324
3,2021-02-03,수,2819,24,2366,27,95,306300,1528,1552,5273,95246,493
4,2021-02-02,화,2795,21,2339,38,94,304772,1904,1925,5269,94753,410
...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,2020-02-25,화,51,13,0,0,0,1823,324,337,618,22,0
348,2020-02-24,월,38,22,0,0,0,1499,407,429,263,22,7
349,2020-02-23,일,16,11,0,0,0,1092,0,11,145,15,0
350,2020-02-22,토,5,3,0,0,0,1092,479,482,115,15,0
351,2020-02-21,금,2,2,0,0,0,613,613,615,15,15,15